### ISSUE TITLE
Bring add cat info button to summary and tracker pages.

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#10]
One comment from Bricks in Twitter that to bring add cat  option in other pages currently it's tucked under token menu and not that visible.

**Comment by ajayZorro** [comment]
This issue is fixed and the Update CAT button is added to the summary and token tracker page. 
![image](https://user-images.githubusercontent.com/100055843/156006311-ef104b14-b4fe-4c6f-8e01-bc5b14b04956.png)

![image](https://user-images.githubusercontent.com/100055843/156006350-ef132a1e-23f1-4c81-bb6e-f168da8d9bda.png)
