### ISSUE TITLE
Balance mismatch for a CAT address

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#11]
It appears they may be an issue with showing current balance for CATs.
This wallet is showing ~198,000 TTT but transactions only account for ~78,000

https://www.spacescan.io/xch/address/xch1r43g4fq7qkxu4yde9uuh9h7uhu053nuqppezgt2jd2gkszvyaflqk03kck

**Comment by BrandtH22** [comment]
Secondary example:
https://www.spacescan.io/xch/address/xch1vkmlwk4tv0pxehe78hv59an2yn4s2fr2t5edqavgudaqwtsjx4tqr7w3gn

It appears the balance of the initial CATs are doubled when other CATs are added.

Likely the system is adding the previous total to the sum of all current unspent CATs and can be updated with a quick fix to the balance logic by ensuring it is creating a new total of unspent CATs rather than adding to the cached amount

**Comment by JagRudh** [comment]
@BrandtH22 This is fixed.

**Comment by spacescan-io** [comment]
@BrandtH22 - Please verify it and lets us know if any found any mismatches.
Thank you for reporting the issue.
