### ISSUE TITLE
Minimum required fees in chia

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#9]
Hola! Can I drop a quicky suggest that would REALLY help some folks out... on the new awesome https://www.spacescan.io/xch/chart/mempool-fees or maybe in the header, it would be helpful if there was a "current recommended fee"
so ppl like me could see really quick what we need to add in to get a tx to mojo itself onto the chain

**Comment by spacescan-io** [comment]
Started working on this and should be ready in few days

**Comment by ajayZorro** [comment]
This Issue is closed and the min fees is added to the home page and mempool fees and cost chart
![image](https://user-images.githubusercontent.com/100055843/155917221-21e2b24c-c2c8-4fdb-9994-34632ef895d3.png)
![image](https://user-images.githubusercontent.com/100055843/155917251-7673f0c3-4291-4839-94f1-190dad8cf7da.png)
